### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'format')

### ISSUE THREAD

**Issue by merolaika** [KayckMatias/zshorts-automatic-shorts-videos-generator#9]
npm run generate

> zshorts@0.0.1 generate
> node index.js

[INFO] - 2024-01-23 14:03:22: ------------ STARTING NEW SHORT ------------

C:\Python\1\zshorts-automatic-shorts-videos-generator\src\services\ffmpeg.js:151
      resolve(metadata.format.duration);
                       ^

TypeError: Cannot read properties of undefined (reading 'format')
    at C:\Python\1\zshorts-automatic-shorts-videos-generator\src\services\ffmpeg.js:151:24
    at handleCallback (C:\Python\1\zshorts-automatic-shorts-videos-generator\node_modules\fluent-ffmpeg\lib\ffprobe.js:106:9)
    at handleExit (C:\Python\1\zshorts-automatic-shorts-videos-generator\node_modules\fluent-ffmpeg\lib\ffprobe.js:190:20)
    at ChildProcess.<anonymous> (C:\Python\1\zshorts-automatic-shorts-videos-generator\node_modules\fluent-ffmpeg\lib\ffprobe.js:233:11)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)

Node.js v20.9.0

**Comment by KayckMatias** [comment]
Hi, do you have ffmpeg installed?

**Comment by merolaika** [comment]
Hello, yep i have..

`

ffmpeg -version
ffmpeg version 6.1.1 Copyright (c) 2000-2023 the FFmpeg developers
built with clang version 17.0.6
configuration: --prefix=/d/bld/ffmpeg_1705436951673/_h_env/Library --cc=clang.exe --cxx=clang++.exe --nm=llvm-nm --ar=llvm-ar --disable-doc --disable-openssl --enable-demuxer=dash --enable-hardcoded-tables --enable-libfreetype --enable-libharfbuzz --enable-libfontconfig --enable-libopenh264 --enable-libdav1d --ld=lld-link --target-os=win64 --enable-cross-compile --toolchain=msvc --host-cc=clang.exe --extra-libs=ucrt.lib --extra-libs=vcruntime.lib --extra-libs=oldnames.lib --strip=llvm-strip --disable-stripping --host-extralibs= --disable-libopenvino --enable-gpl --enable-libx264 --enable-libx265 --enable-libaom --enable-libsvtav1 --enable-libxml2 --enable-pic --enable-shared --disable-static --enable-version3 --enable-zlib --enable-libopus --pkg-config=/d/bld/ffmpeg_1705436951673/_build_env/Library/bin/pkg-config
libavutil      58. 29.100 / 58. 29.100
libavcodec     60. 31.102 / 60. 31.102
libavformat    60. 16.100 / 60. 16.100
libavdevice    60.  3.100 / 60.  3.100
libavfilter     9. 12.100 /  9. 12.100
libswscale      7.  5.100 /  7.  5.100
libswresample   4. 12.100 /  4. 12.100
libpostproc    57.  3.100 / 57.  3.100
`
